### ISSUE TITLE
echo_subrequest_async with cosocket

### ISSUE THREAD

**Issue by GuillaumeMar** [agentzh/old-openresty#3]
Hi,

I'm reading incoming content of nginx with cosocket, like this :

local clientsock = ngx.req.socket()
...
local req_body, err, partial = clientsock:receive(2048)
...

And then I call an async method with the req_body, for each stream:

echo_subrequest_async PUT /test -q 'md5=$arg_md5'  -b $echo_request_body;

But after one request done I got this error:
2012/05/04 13:12:42 [error] 20906#0: *1 lua socket read timed out while sending to client, client: 1.2.3.4, server: , request: "PUT /file.tgz HTTP/1.1", host: "xxxx" 

With echo_subrequest it works good.

Any idea? :)
Thx

**Comment by HakChealKim** [comment]
configure file;
my mac can not find the configure file, whats the root cause?

**Comment by agentzh** [comment]
Wrong project. The old openresty is dead.
